force-app/main/default/objects/TRG_TriggerActivationSettings__c/TRG_TriggerActivationSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This settings will allow to define if triggers, flows, validation rules must be activated or not.</description>
    <label>TRG Trigger Activation Settings</label>
</CustomObject>

force-app/main/default/objects/TRG_TriggerActivationSettings__c/fields/TRG_Disable_All_Triggers__c.field-meta.xml
<CustomField>
    <fullName>TRG_Disable_All_Triggers__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>When checked, all he triggers will be disabled independently of those listed in the Disable Trigger List</inlineHelpText>
    <label>Disable All Triggers</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TRG_TriggerActivationSettings__c/fields/TRG_Triggers_To_Disable_List__c.field-meta.xml
<CustomField>
    <fullName>TRG_Triggers_To_Disable_List__c</fullName>
    <inlineHelpText>List the trigger names to be disabled, separated by a semicolon.</inlineHelpText>
    <label>Triggers To Disable List</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/UTL_TriggerControl.cls
/**
 * @description       : This class controls the enabling and disabling of triggers based on user settings.
 * @author            : imrudrakarmakar
 * @group             : 
 * @last modified on  : 08-07-2025
 * @last modified by  : imrudrakarmakar
**/
public with sharing class UTL_TriggerControl {

    @TestVisible private static Set<String> disabledTriggers = new Set<String>();
    @TestVisible private static Boolean disableAllTriggers = false;
    @TestVisible private static Boolean isInitialized = false;

    @TestVisible private static void initialize() {
        if (isInitialized) return;
        isInitialized = true;

        TRG_TriggerActivationSettings__c settings = TRG_TriggerActivationSettings__c.getInstance(UserInfo.getUserId());
        if (settings == null) {
            settings = TRG_TriggerActivationSettings__c.getOrgDefaults();
        }

        if (settings != null) {
            disableAllTriggers = settings.TRG_Disable_All_Triggers__c;

            if (!String.isBlank(settings.TRG_Triggers_To_Disable_List__c)) {
                List<String> items = settings.TRG_Triggers_To_Disable_List__c.split(',');
                for (String item : items) {
                    disabledTriggers.add(item.trim().toLowerCase());
                }
            }
        }
    }

    public static Boolean isTriggerDisabled(String triggerKey) {
        initialize();
        if (disableAllTriggers) return true;
        return disabledTriggers.contains(triggerKey.toLowerCase());
    }

}